# Generated by Django 2.2.9 on 2020-05-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20200516_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('False', 'False'), ('True', 'True'), ('New', 'New')], default='New', max_length=10),
        ),
    ]
